version: '3.3' # 3.9
services:

  mysql:
    image: mysql:8.0
    container_name: witcher-mysql
    # build:
      # context: .
      # dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: the_witcher_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r
    networks:
      - witcher-network
    ports:
      - "3306:3306"
    volumes:
      - witcher-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tomcat:
    image: tomcat:10.1.9-jdk17
    container_name: witcher-tomcat
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    networks:
      - witcher-network
    volumes:
      - ../code/target/:/usr/local/tomcat/webapps/ # Archivo WAR correctamente mapeado

volumes:
  witcher-data:

networks:
  witcher-network:
    driver: bridge
